// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0_6-jtomtnqhMcDaiWV0m5tKWZ6WmOXY',
    appId: '1:799779020711:web:822717f57df6c6f3406082',
    messagingSenderId: '799779020711',
    projectId: 'degdeg-ceb1d',
    authDomain: 'degdeg-ceb1d.firebaseapp.com',
    storageBucket: 'degdeg-ceb1d.appspot.com',
    measurementId: 'G-1PPHNYGF1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs0oFu_xg9IKIpZZWVrZzY0Q8m9ALWTKg',
    appId: '1:799779020711:android:86e69601b9685f28406082',
    messagingSenderId: '799779020711',
    projectId: 'degdeg-ceb1d',
    storageBucket: 'degdeg-ceb1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOq-hrfQtwdTCaRA8fjy7eluIoyPAf_4',
    appId: '1:799779020711:ios:adb140d28d41983a406082',
    messagingSenderId: '799779020711',
    projectId: 'degdeg-ceb1d',
    storageBucket: 'degdeg-ceb1d.appspot.com',
    iosBundleId: 'com.example.degdeg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOOq-hrfQtwdTCaRA8fjy7eluIoyPAf_4',
    appId: '1:799779020711:ios:a7c1d1edcecc65d6406082',
    messagingSenderId: '799779020711',
    projectId: 'degdeg-ceb1d',
    storageBucket: 'degdeg-ceb1d.appspot.com',
    iosBundleId: 'com.example.degdeg.RunnerTests',
  );
}
